CREATE TABLE `student_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`onboardingCompleted` int NOT NULL DEFAULT 0,
	`onboardingStep` int NOT NULL DEFAULT 0,
	`preferredName` varchar(120),
	`gradeLevel` enum('9','10','11','12','mezun'),
	`examYear` int,
	`targetScoreType` enum('SAY','EA','SOZ','DIL','TYT','belirsiz'),
	`currentTytNet` varchar(40),
	`currentAytNet` varchar(40),
	`mockExamFrequency` varchar(60),
	`strongSubjectsJson` text,
	`weakSubjectsJson` text,
	`hasPriorStudyPlan` int,
	`targetUniversity` varchar(180),
	`targetDepartment` varchar(180),
	`targetRanking` varchar(60),
	`mainGoal` text,
	`shortTermGoal` text,
	`longTermGoal` text,
	`dailyStudyDuration` int,
	`availableStudyDaysJson` text,
	`preferredStudyTimesJson` text,
	`preferredStudyMethodsJson` text,
	`studyObstacles` text,
	`coachingExpectationsJson` text,
	`notificationPreference` varchar(60),
	`coachingStyle` enum('destekleyici','disiplinli','kisa_net','detayli','dengeli'),
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `student_profiles_userId_unique` UNIQUE(`userId`)
);
